# World Happiness

## 1. Import Libraries and Dependencies

In [8]:
# Import dependencies
import pandas as pd
from pathlib import Path

## 2. Set File Path to CSV using Pathlib

In [9]:
# Create reference to CSV file
# Hint - the file path may require some extra steps..
filepath = Path('../Resources/world_happiness.csv')

## 3. Import CSV into Pandas DataFrame

In [10]:
# Import the CSV into a pandas DataFrame
df = pd.read_csv(filepath)
df

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
154,Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

## 4. Set Index and Sort Index in Ascending Order

In [11]:
# Set new index to Country
df.set_index('Country',inplace=True)

# Sort the new dataframe alphabetically
df.sort_index(inplace=True)
df

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
Country,,,,,,,,,,,
Afghanistan,141,3.794,3.873661,3.714338,0.401477,0.581543,0.180747,0.106180,0.311871,0.061158,2.150801
Albania,109,4.644,4.752464,4.535536,0.996193,0.803685,0.731160,0.381499,0.201313,0.039864,1.490442
Algeria,53,5.872,5.978286,5.765714,1.091864,1.146217,0.617585,0.233336,0.069437,0.146096,2.567604
Angola,140,3.795,3.951642,3.638358,0.858428,1.104412,0.049869,0.000000,0.097926,0.069720,1.614482
Argentina,24,6.599,6.690085,6.507915,1.185295,1.440451,0.695137,0.494519,0.109457,0.059740,2.614005
...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,82,5.250,5.370032,5.129968,1.128431,1.431338,0.617144,0.153997,0.065020,0.064491,1.789464
Vietnam,94,5.074,5.147281,5.000719,0.788548,1.277491,0.652169,0.571056,0.234968,0.087633,1.462319
Yemen,146,3.593,3.692750,3.493250,0.591683,0.935382,0.310081,0.249464,0.104125,0.056767,1.345601
Zambia,116,4.514,4.644106,4.383894,0.636407,1.003187,0.257836,0.461603,0.249580,0.078214,1.826705
Zimbabwe,138,3.875,3.978700,3.771300,0.375847,1.083096,0.196764,0.336384,0.189143,0.095375,1.597970

## 5. Select the Happiness Score for Vietnam

In [54]:
# Grab the data contained within the row of a country of your choice and the "Happiness.Score" column
# Print the result as "<country's name> happiness score for 2017 was <happiness score>"
data = df.loc[['Brazil'],['Happiness.Score']]
print(f'{data.index[0]}\'s happiness score for 2017 was {data["Happiness.Score"]}')

Brazil's happiness score for 2017 was Country
Brazil    6.635
Name: Happiness.Score, dtype: float64

In [55]:
data

         Happiness.Score
Country
Brazil             6.635

## 6. Select the Happiness Rank and Score for Belgium, Belize, Benin, Bhutan, and Bolivia

In [32]:
# Grab all rows of data from "Belgium" to "Bolivia" and the columns from "Happiness.Rank" to "Happiness.Score"
# Hint - in order to view more data you will need to increase the dataframe's head
data = df.loc[['Belgium','Belize','Benin','Bhutan','Bolivia'],['Happiness.Rank','Happiness.Score']]
data

         Happiness.Rank  Happiness.Score
Country
Belgium              17            6.891
Belize               50            5.956
Benin               143            3.657
Bhutan               97            5.011
Bolivia              58            5.823

## 7. Select the Freedom and Government Trust for Every Country

In [57]:
# Select all rows and only display the columns for "Freedom" and "Trust..Government.Corruption." 
sample = df.loc[:,['Freedom','Trust..Government.Corruption.']]
sample

              Freedom  Trust..Government.Corruption.
Country
Afghanistan  0.106180                       0.061158
Albania      0.381499                       0.039864
Algeria      0.233336                       0.146096
Angola       0.000000                       0.069720
Argentina    0.494519                       0.059740
...               ...                            ...
Venezuela    0.153997                       0.064491
Vietnam      0.571056                       0.087633
Yemen        0.249464                       0.056767
Zambia       0.461603                       0.078214
Zimbabwe     0.336384                       0.095375

[155 rows x 2 columns]

## 8. Select all the Countries Where GDP is Greater than or Equal to 1.6

In [61]:
# Select all rows where the GDP per capita has a value greater than or equal to 1.6
sample2 = df.loc[df['Economy..GDP.per.Capita.'] >= 1.6]
sample2

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
Country,,,,,,,,,,,
Kuwait,39,6.105,6.191957,6.018043,1.632952,1.259699,0.632106,0.496338,0.228290,0.215160,1.640425
Luxembourg,18,6.863,6.923686,6.802314,1.741944,1.457584,0.845089,0.596628,0.283181,0.318834,1.619512
Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
Qatar,35,6.375,6.568477,6.181523,1.870766,1.274297,0.710098,0.604131,0.330474,0.439299,1.145464
Singapore,26,6.572,6.636723,6.507277,1.692278,1.353814,0.949492,0.549841,0.345966,0.464308,1.216362
United Arab Emirates,21,6.648,6.722047,6.573952,1.626343,1.266410,0.726798,0.608345,0.360942,0.324490,1.734704

## 9. Select all the Countries Where the Happiness Score is Greater than or Equal to 5 and GDP is Less than or Equal to 1

In [67]:
# Select all rows that have a happiness score greater than or equal 5 and a GDP score less than or equal 1
sample3 = df.loc[(df['Happiness.Score'] >= 5) & (df['Economy..GDP.per.Capita.'] <= 1)]
sample3

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
Country,,,,,,,,,,,
Belize,50,5.956,6.197242,5.714757,0.907975,1.081418,0.450192,0.547509,0.240016,0.096581,2.631956
Bhutan,97,5.011,5.079335,4.942666,0.885416,1.340127,0.495879,0.501538,0.474055,0.173380,1.140184
Bolivia,58,5.823,5.903977,5.742023,0.833757,1.227619,0.473630,0.558733,0.225561,0.060478,2.443279
Bosnia and Herzegovina,90,5.182,5.276336,5.087665,0.982409,1.069336,0.705186,0.204403,0.328867,0.000000,1.892173
El Salvador,45,6.003,6.108635,5.897364,0.909784,1.182125,0.596019,0.432453,0.078258,0.089981,2.714594
Guatemala,29,6.454,6.566874,6.341126,0.872002,1.255585,0.540240,0.531311,0.283488,0.077223,2.893891
Honduras,91,5.181,5.301583,5.060418,0.730573,1.143945,0.582569,0.348080,0.236189,0.073345,2.065811
Indonesia,81,5.262,5.352889,5.171112,0.995539,1.274445,0.492346,0.443323,0.611705,0.015317,1.429477
Jamaica,76,5.311,5.581399,5.040601,0.925579,1.368218,0.641022,0.474307,0.233818,0.055268,1.612326
Jordan,74,5.336,5.448410,5.223590,0.991012,1.239089,0.604590,0.418421,0.172170,0.119803,1.791177
Kosovo,78,5.279,5.364848,5.193152,0.951484,1.137854,0.541452,0.260288,0.319931,0.057472,2.010541
Kyrgyzstan,98,5.004,5.089920,4.918080,0.596220,1.394239,0.553458,0.454943,0.428580,0.039439,1.536723
Moldova,56,5.838,5.908371,5.767629,0.728871,1.251826,0.589465,0.240729,0.208779,0.010091,2.807808
Morocco,84,5.235,5.318341,5.151659,0.878115,0.774864,0.597711,0.408158,0.032210,0.087763,2.456189
Nicaragua,43,6.071,6.186584,5.955417,0.737299,1.287216,0.653096,0.447552,0.301674,0.130688,2.513931
Nigeria,95,5.074,5.209500,4.938500,0.783756,1.215770,0.056916,0.394953,0.230947,0.026122,2.365391
Pakistan,80,5.269,5.359984,5.178016,0.726884,0.672691,0.402048,0.235215,0.315446,0.124348,2.792489
Paraguay,70,5.493,5.577381,5.408619,0.932537,1.507285,0.579251,0.473508,0.224151,0.091066,1.685333
Philippines,72,5.430,5.545335,5.314665,0.857699,1.253918,0.468009,0.585215,0.193513,0.099332,1.972605
Somalia,93,5.151,5.242484,5.059516,0.022643,0.721151,0.113989,0.602127,0.291631,0.282410,3.117485
Tajikistan,96,5.041,5.111426,4.970574,0.524714,1.271463,0.529235,0.471567,0.248998,0.146377,1.849049
Uzbekistan,47,5.971,6.065538,5.876463,0.786441,1.548969,0.498273,0.658249,0.415984,0.246528,1.816914
Vietnam,94,5.074,5.147281,5.000719,0.788548,1.277491,0.652169,0.571056,0.234968,0.087633,1.462319